### ISSUE TITLE
Error adding the extension to the extension list

### ISSUE THREAD

**Issue by yank07** [ckan/ckanext-drupal7#2]
Hello,

I have try to configure the extension, I put this parameters in my configuration, 
ckanext.drupal7.domain = localhost
ckanext.drupal7.sysadmin_role = ckan admin
ckanext.drupal7.connection = postgresql://drupal:*****(mypass)@localhost/drupal

and when I put drupal7 in the extension list I have this error

TypeError: update_config() takes exactly 2 arguments (1 given); got ({'debug'...lt'}, app_instance_uuid=..., beaker.session.key=..., beaker.session.secret=..., cache_dir=..., ckan.activity_streams_email_notifications=..., ckan.auth.anon_create_dataset=..., ckan.auth.create_dataset_if_not_in_organization=..., ckan.auth.create_unowned_dataset=..., ckan.auth.create_user_via_api=..., ckan.auth.create_user_via_web=..., ckan.auth.roles_that_cascade_to_sub_groups=..., ckan.auth.user_create_groups=..., ckan.auth.user_create_organizations=..., ckan.auth.user_delete_groups=..., ckan.auth.user_delete_organizations=..., ckan.datastore.read_url=..., ckan.datastore.write_url=..., ckan.favicon=..., ckan.feeds.author_link=..., ckan.feeds.author_name=..., ckan.feeds.authority_name=..., ckan.feeds.date=..., ckan.gravatar_default=..., ckan.harvest.mq.type=..., ckan.locale_default=..., ckan.locale_order=..., ckan.locales_filtered_out=..., ckan.locales_offered=..., ckan.plugins=..., ckan.preview.direct=..., ckan.preview.loadable=..., ckan.site_description=..., ckan.site_id=..., ckan.site_logo=..., ckan.site_title=..., ckan.site_url=..., ckan.storage_path=..., ckanext.drupal7.connection=..., ckanext.drupal7.domain=..., ckanext.drupal7.sysadmin_role=..., disqus.name=..., email_to=..., error_email_from=..., full_stack=..., googleanalytics.account=..., googleanalytics.id=..., googleanalytics.password=..., googleanalytics.username=..., smtp.mail_from=..., smtp.password=..., smtp.server=..., smtp.starttls=..., smtp.user=..., solr_url=..., sqlalchemy.url=..., who.config_file=..., who.log_file=..., who.log_level=...), wanted (conf, full_stack=True, static_files=True, **app_conf)

**Comment by mikekberg** [comment]
i've fixed this bug and issued a pull request
